---
/detect_level_crossing:
  ros__parameters:
    detect:
      level:
        red:
          hue_l: 0
          hue_h: 22
          saturation_l: 173
          saturation_h: 255
          lightness_l: 106
          lightness_h: 255
